server:
  port: 2333
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.1"
      snapshot: false
  server:
    password: "youshallnotpass"
    sources:
      youtube: false
      soundcloud: true
      bandcamp: true
      twitch: true
      vimeo: true
      http: true
      local: false

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    oauth:
      enabled: true
      refreshToken: "YOUR_YOUTUBE_REFRESH_TOKEN"
      skipInitialization: true
    clients:
      - WEB
      - ANDROID_VR
      - TVHTML5
      - WEBEMBEDDED

logging:
  level:
    root: INFO
    lavalink: DEBUG
    dev.lavalink.youtube: DEBUG
    com.sedmelluq.discord.lavaplayer.tools.ExceptionTools: DEBUG
